# Generated by Django 2.2.10 on 2020-07-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20200709_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertointerview',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.Question'),
        ),
        migrations.AlterField(
            model_name='usertointerview',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='interview.Interview'),
        ),
    ]
