# Generated by Django 2.2.10 on 2020-07-09 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20200709_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date_end',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date_start',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='usertointerview',
            name='answer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usertointerview',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Interview'),
        ),
        migrations.AlterField(
            model_name='usertointerview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to=settings.AUTH_USER_MODEL),
        ),
    ]
